### ISSUE TITLE
Realizar esquema de la interfaz gráfica

### ISSUE THREAD

**Issue by hros19** [hros19/mvc-java-proyecto-ejemplo#5]

**Comment by GalyEspinoza** [comment]
Buenas, solo quería informar de que ya tengo casi completo el bosquejo (hay algunos detalles de implementación que podemos hablar en nuestra reunión de hoy) , únicamente como un previo aviso tengo una pequeña duda referente a la "tabla de amortización" que es mencionada en varias funcionalidades....

**Comment by GalyEspinoza** [comment]
Entendido
